files:
  ignore:
    - "app/_assets/vendor/**/*.*"
    - "public/**/*.*"
options:
  formatter: stylish
  merge-default-rules: true
rules:
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero:
    - 2
    - include: true
  nesting-depth:
    - 1
    - max-depth: 3
  no-css-comments: 0
  trailing-semicolon: 2
