# Format as stylish and bring in default rules
options:
  formatter: stylish
  merge-default-rules: true

# Custom overrides of default rules
rules:

  # Don't force elements to be nested (this should be left up to discretion, nesting can get nuts)
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Force leading zeros for decimal numbers
  leading-zero:
    - 2
    - include: true

  # Increase nesting depth to 3 levels
  nesting-depth:
    - 1
    - max-depth: 3

  # Don't enforce any specific style of commenting
  no-css-comments: 0
