language: "node_js"
node_js:
  - "5.4.1"
before_install:
  - "rvm install 2.3.0"
install:
  - npm install
  - "npm install -g surge"
  - "bundle install --path vendor/bundle"
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master"} ] && npm run build && surge ./public || false'
