language: "node_js"
node_js:
  - "6.2.2"
before_install:
  - "rvm install 2.3.1"
install:
  - npm install
  - "bundle install"
script:
  - npm run lint
  - npm run build
before_deploy:
  - "npm install -g surge"
deploy:
  provider: script
  script: "surge ./public"
  skip_cleanup: true
branches:
  only:
    - master
