name: "Patrick Hooper"
description: "Portfolio Site"
url: "http://patrick.hoopr.io"
markdown: rdiscount
permalink: pretty
exclude: [bin, .gems, Gemfile, Gemfile.lock, Icon]
gems:
  - jekyll-sitemap
collections:
  home:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:title/
