name: "Patrick Hooper"
description: "Portfolio Site"
url: "http://patrick.hoopr.io"
markdown: rdiscount
permalink: pretty
exclude: ["CNAME", "README.md", "node_modules", "Gemfile", "Gemfile.lock", "package.json", "gulpfile.js", "img/portfolio/university-of-michigan-athletics", "img/portfolio/wgi*", "sass", "js/app.js", "resources/logos", "*.psd", "*.ai", "vendor"]
gems:
  - jekyll-sitemap
collections:
  home:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:title/
