name: "Patrick Hooper"
description: "Portfolio Site"
url: "http://patrick.hoopr.io"
markdown: rdiscount
permalink: pretty
exclude: ["CNAME", "README.md", "Gemfile", "Gemfile.lock", "package.json", "node_modules", "gulpfile.js", "docs/ai", "docs/psd", "img/portfolio/university-of-michigan-athletics", "img/portfolio/wgi*", "js/app.js", "sass",  "vendors"]
gems:
  - jekyll-sitemap
collections:
  home:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:title/
