title: Patrick Hooper
description: "Web (app) developer, life enthusiast, University of Michigan alumnus, and all-around neat guy living in Ann Arbor, MI. Also, Marie Hooper's biggest fan."
url: "https://patrickhooper.me"
source: "./app"
destination: "./public"
collections:
  home:
    output: false
  projects:
    output: true
    permalink: "/projects/:title/"
gems:
  - "jekyll-sitemap"
permalink: pretty
