name: "Patrick Hooper"
description: "Portfolio Site"
url: "http://patrickhooper.github.io"
markdown: rdiscount
permalink: pretty
exclude: [bin, .gems, Gemfile, Gemfile.lock, Icon]
sass:
  style: :compressed
collections:
  home:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:title/
