name: "Patrick Hooper"
description: "The portfolio site for Patrick Hooper. Web (App) Developer, Life Enthusiast, Technology Fanboy, Happily Married, Cheesecake Evangelist, World Traveler, and more. Currently located in Ann Arbor, Michigan."
url: "http://patrick.hoopr.io"
collections:
  home:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:title/
exclude: ["CNAME", "README.md", "Gemfile", "Gemfile.lock", "package.json", "node_modules", "gulpfile.js"]
gems:
  - jekyll-sitemap
markdown: rdiscount
permalink: pretty
