title: Patrick Hooper
description: "The portfolio site for Patrick Hooper. Web (App) Developer, Life Enthusiast, Technology Fanboy, Happily Married, Cheesecake Evangelist, World Traveler, and more. Currently living in Ann Arbor, Michigan as a proud University of Michigan grad - Go Blue!"
url: "http://patrick.hoopr.io"
source: "../app"
destination: "../public"
collections:
  home:
    output: false
  projects:
    output: true
    permalink: "/projects/:title/"
gems:
  - "jekyll-sitemap"
permalink: pretty
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
